name: .NET Aspire Samples CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: Build Samples

    steps:
    - uses: actions/checkout@v3

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: "global.json"

    - name: Auth NuGet
      run: |
        dotnet nuget update source dotnet-final --username az --password ${{ secrets.AZURE_DEVOPS_TOKEN }} --configfile NuGet.config
        dotnet nuget update source dotnet-tools-internal --username az --password ${{ secrets.AZURE_DEVOPS_TOKEN }} --configfile NuGet.config
    
    - name: Build
      run: ${{ matrix.os == 'ubuntu-latest' && './build.sh' || '.\build.cmd' }}

            